# -----------------------------------------------------------
# Jekyllの基本設定（全ブログ共通）
# -----------------------------------------------------------
title: Cloud Blog Platform
email: system@cloudblog.com
description: クラウドブログ管理システム